settings:
  title: 'Trucky Status Page'
  url: 'https://status.truckyapp.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-trucykapp-com # unique identifier
    name: API Backend
    description: '' # default=empty
    url: 'https://api.truckyapp.com/docs' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false,
    hideUrl: false

  - id: truckyapp-com
    name: Trucky Official Site
    description: ''
    url: 'https://truckyapp.com'
    method: GET
    expectStatus: 200
    hideUrl: false

  - id: web-truckyapp-com
    name: Trucky Web App
    url: 'https://web.truckyapp.com/'
    method: GET
    expectStatus: 200
    hideUrl: false

  - id: trucky-events
    name: Trucky Events
    url: 'https://trucky.events/'
    method: GET
    expectStatus: 200
    hideUrl: false

  - id: tiles-truckyapp-com
    name: Trucky Map Tiles Server
    url: 'https://tiles.truckyapp.com/'
    method: GET
    expectStatus: 403
    hideUrl: true